#!/usr/bin/env bash
# Scaffolds .env for the LiteLLM + Open WebUI PoC.
# Generates the random secrets, then prompts for provider API keys.
# Safe to re-run: it won't clobber an existing .env unless you pass --force.

set -euo pipefail

cd "$(dirname "$0")"
ENV_FILE=".env"

# --- guard against overwriting --------------------------------------------
if [[ -f "$ENV_FILE" && "${1:-}" != "--force" ]]; then
  echo "✋  $ENV_FILE already exists. Re-run with --force to overwrite it."
  exit 1
fi

# --- need openssl ----------------------------------------------------------
if ! command -v openssl >/dev/null 2>&1; then
  echo "❌  openssl not found. Install it and re-run."
  exit 1
fi

echo "🔐  Generating secrets..."
LITELLM_MASTER_KEY="sk-$(openssl rand -hex 24)"
LITELLM_SALT_KEY="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 16)"
WEBUI_SECRET_KEY="$(openssl rand -hex 32)"

# --- prompt for provider keys (input hidden) -------------------------------
echo
echo "Paste your provider API keys (leave blank to fill in later)."
read -rsp "  OpenAI API key (sk-...):      " OPENAI_API_KEY;    echo
read -rsp "  Anthropic API key (sk-ant-...): " ANTHROPIC_API_KEY; echo
read -rsp "  Gemini API key (AIza...):       " GEMINI_API_KEY;    echo
read -rsp "  DeepSeek API key (sk-...):      " DEEPSEEK_API_KEY;  echo

OPENAI_API_KEY="${OPENAI_API_KEY:-sk-REPLACE_ME}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-sk-ant-REPLACE_ME}"
GEMINI_API_KEY="${GEMINI_API_KEY:-AIza-REPLACE_ME}"
DEEPSEEK_API_KEY="${DEEPSEEK_API_KEY:-sk-REPLACE_ME}"

# --- write .env ------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date)
# --- LiteLLM admin / signing ---
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
LITELLM_SALT_KEY=${LITELLM_SALT_KEY}

# --- Postgres ---
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# --- Open WebUI ---
WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}

# --- Provider API keys ---
OPENAI_API_KEY=${OPENAI_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
GEMINI_API_KEY=${GEMINI_API_KEY}
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
EOF

chmod 600 "$ENV_FILE"

echo
echo "✅  Wrote $ENV_FILE (chmod 600)."
echo "   Master key (for LiteLLM admin UI login): ${LITELLM_MASTER_KEY}"
[[ "$OPENAI_API_KEY"    == sk-REPLACE_ME      ]] && echo "   ⚠️  OpenAI key not set — edit $ENV_FILE before starting."
[[ "$ANTHROPIC_API_KEY" == sk-ant-REPLACE_ME  ]] && echo "   ⚠️  Anthropic key not set — edit $ENV_FILE before starting."
[[ "$GEMINI_API_KEY"    == AIza-REPLACE_ME    ]] && echo "   ⚠️  Gemini key not set — edit $ENV_FILE before starting."
[[ "$DEEPSEEK_API_KEY"  == sk-REPLACE_ME      ]] && echo "   ⚠️  DeepSeek key not set — edit $ENV_FILE before starting."
echo
echo "Next:  docker compose up -d"
